
name: Docker

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/qwerascal/decembertask .
      - run: docker push ghcr.io/qwerascal/decembertask
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 729628521
          token: 6400997566:AAHoOlJocgpLN1-0Gh5EwQv5UxTLc5l3MaY
          
          message: |
           Всё работает
            
            Репоп ${{github.repository}}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker run ghcr.io/qwerascal/decembertask
